// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ova_competition_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CompetitionServiceClient is the client API for CompetitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompetitionServiceClient interface {
	CreateCompetition(ctx context.Context, in *CreateCompetitionRequest, opts ...grpc.CallOption) (*CompetitionResponse, error)
	DescribeCompetition(ctx context.Context, in *DescribeCompetitionRequest, opts ...grpc.CallOption) (*CompetitionResponse, error)
	ListCompetitions(ctx context.Context, in *ListCompetitionsRequest, opts ...grpc.CallOption) (*ListCompetitionsResponse, error)
	RemoveCompetition(ctx context.Context, in *RemoveCompetitionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type competitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompetitionServiceClient(cc grpc.ClientConnInterface) CompetitionServiceClient {
	return &competitionServiceClient{cc}
}

func (c *competitionServiceClient) CreateCompetition(ctx context.Context, in *CreateCompetitionRequest, opts ...grpc.CallOption) (*CompetitionResponse, error) {
	out := new(CompetitionResponse)
	err := c.cc.Invoke(ctx, "/ova.competition.api.CompetitionService/CreateCompetition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) DescribeCompetition(ctx context.Context, in *DescribeCompetitionRequest, opts ...grpc.CallOption) (*CompetitionResponse, error) {
	out := new(CompetitionResponse)
	err := c.cc.Invoke(ctx, "/ova.competition.api.CompetitionService/DescribeCompetition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) ListCompetitions(ctx context.Context, in *ListCompetitionsRequest, opts ...grpc.CallOption) (*ListCompetitionsResponse, error) {
	out := new(ListCompetitionsResponse)
	err := c.cc.Invoke(ctx, "/ova.competition.api.CompetitionService/ListCompetitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionServiceClient) RemoveCompetition(ctx context.Context, in *RemoveCompetitionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ova.competition.api.CompetitionService/RemoveCompetition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompetitionServiceServer is the server API for CompetitionService service.
// All implementations must embed UnimplementedCompetitionServiceServer
// for forward compatibility
type CompetitionServiceServer interface {
	CreateCompetition(context.Context, *CreateCompetitionRequest) (*CompetitionResponse, error)
	DescribeCompetition(context.Context, *DescribeCompetitionRequest) (*CompetitionResponse, error)
	ListCompetitions(context.Context, *ListCompetitionsRequest) (*ListCompetitionsResponse, error)
	RemoveCompetition(context.Context, *RemoveCompetitionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCompetitionServiceServer()
}

// UnimplementedCompetitionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCompetitionServiceServer struct {
}

func (UnimplementedCompetitionServiceServer) CreateCompetition(context.Context, *CreateCompetitionRequest) (*CompetitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompetition not implemented")
}
func (UnimplementedCompetitionServiceServer) DescribeCompetition(context.Context, *DescribeCompetitionRequest) (*CompetitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeCompetition not implemented")
}
func (UnimplementedCompetitionServiceServer) ListCompetitions(context.Context, *ListCompetitionsRequest) (*ListCompetitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCompetitions not implemented")
}
func (UnimplementedCompetitionServiceServer) RemoveCompetition(context.Context, *RemoveCompetitionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCompetition not implemented")
}
func (UnimplementedCompetitionServiceServer) mustEmbedUnimplementedCompetitionServiceServer() {}

// UnsafeCompetitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompetitionServiceServer will
// result in compilation errors.
type UnsafeCompetitionServiceServer interface {
	mustEmbedUnimplementedCompetitionServiceServer()
}

func RegisterCompetitionServiceServer(s grpc.ServiceRegistrar, srv CompetitionServiceServer) {
	s.RegisterService(&CompetitionService_ServiceDesc, srv)
}

func _CompetitionService_CreateCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompetitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).CreateCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.competition.api.CompetitionService/CreateCompetition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).CreateCompetition(ctx, req.(*CreateCompetitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_DescribeCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeCompetitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).DescribeCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.competition.api.CompetitionService/DescribeCompetition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).DescribeCompetition(ctx, req.(*DescribeCompetitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_ListCompetitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCompetitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).ListCompetitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.competition.api.CompetitionService/ListCompetitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).ListCompetitions(ctx, req.(*ListCompetitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitionService_RemoveCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCompetitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServiceServer).RemoveCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ova.competition.api.CompetitionService/RemoveCompetition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServiceServer).RemoveCompetition(ctx, req.(*RemoveCompetitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompetitionService_ServiceDesc is the grpc.ServiceDesc for CompetitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompetitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ova.competition.api.CompetitionService",
	HandlerType: (*CompetitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompetition",
			Handler:    _CompetitionService_CreateCompetition_Handler,
		},
		{
			MethodName: "DescribeCompetition",
			Handler:    _CompetitionService_DescribeCompetition_Handler,
		},
		{
			MethodName: "ListCompetitions",
			Handler:    _CompetitionService_ListCompetitions_Handler,
		},
		{
			MethodName: "RemoveCompetition",
			Handler:    _CompetitionService_RemoveCompetition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "competition.proto",
}
